version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo "holler, human" # added command for testing
      - run: echo "this runs on development" # added command for testing branches
      - run: ssh -v ubuntu@ec2-3-94-166-176.compute-1.amazonaws.com
      - run: echo "Hello world!" #Test connection between CCI and AWS
