version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo $test_env_1
      #- run: ssh ubuntu@3.94.166.176
      - run: echo "Hello world!" #Test connection between CCI and AWS
      - run: |
          if ["{$test_conditional}" == "1"]; then
          echo test_conditional_true
          fi
      - run: |
          if [$test_conditional != 1]; then
          echo test_conditional_false
          fi
  deploy:
      machine: true
      steps:
          - run: echo "deploy phase!"
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: Test1
      - deploy:
          context: Test1
